mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls', namespace="polls")),
    path('',RedirectView.as_view(url='polls/'))
    
]

mysite/polls/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
app_name = 'polls'
urlpatterns = [
    path('', views.home),
    path('<int:question_id>/', views.detail),
    path('<int:question_id>/vote/', views.vote, name="vote"),
    path('<int:question_id>/results/', views.results, name="results"),
]

mysite/polls/models.py
from django.db import models
# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=255)
    
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    choice_text = models.CharField(max_length=255)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
# Create your views here.
from .models import Question

def home(requests):
    all_questions = Question.objects.all()
    data = {
        'questions_list' : all_questions
    }
    return render(requests, 'polls/index.html', context=data)

def detail(requests,question_id):

    question = Question.objects.get(pk=question_id)
    data = {
        'question': question
    }
    return render(requests, 'polls/detail.html', context=data)

def vote(requests, question_id):
    question = Question.objects.get(pk=question_id)
    selected_choice = question.choice_set.get(pk=requests.POST["choice"])
    selected_choice.votes += 1
    selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

def results(requests, question_id):
    question = Question.objects.get(pk=question_id)
    data = {
        'question': question
    }
    return render(requests, 'polls/result.html', context=data)

mysite/polls/templates/polls/base.html
{% load static %}
<html>
    <head>
        <title>Hello its a TItle</title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />

    </head>
    
<body>
{% block content %}
{% endblock %}
</body>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</html>

mysite/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block content %}
Question : {{question.question_text}}
<form action="{% url 'polls:vote' question.id %}" method="POST">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
   <input type="radio" name="choice" value="{{choice.id}}">
    <label>{{choice.choice_text}}</label> 
    {% endfor %}
    <br>
    <input type="submit" value="Vote">
</form>

{% endblock %}

mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block content %}
<h1>Say me about you !</h1>
<ul>
    {% for question in questions_list %}
        <li><a href="{{question.pk}}">{{question}}</a></li>
    {% endfor %}
</ul>

{% endblock %}

mysite/polls/templates/polls/result.html
{% extends 'polls/base.html' %}
{% block content %}

<h1>Result of {{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:results' question.id %}">Vote again?</a>

{% endblock %}